### ISSUE TITLE
.NET 5.0.100/101 remote Raspberry debugging doesn't work

### ISSUE THREAD

**Issue by myg3l** [nforgeio/RaspberryDebugger#15] opened 2020-11-20 12:10 UTC
"Unable to attach to CoreCLR. Unknown Error: 0x80131c4f". 

Appears to be some .Net 5.0.100 runtime or debugger issue. Workaround by using 3.1.404 on rpi & host

https://github.com/OmniSharp/omnisharp-vscode/issues/4210

**Comment by jefflill** [comment] 2020-11-20 17:57
.NET 5 worked OK during my testing debugging remotely on a Raspberry.  Have you tried the **Raspberry Debugger** and seen a failure?  At this point, I'm probably the only person to actually use the thing.

**Comment by myg3l** [comment] 2020-11-20 20:01
I've also used the https://github.com/radutomy/VSRemoteDebugger

Both VSRemoteDebugger and Raspberry Debugger fails with the .NET 5.0.100 for me. Both works if I revert to the .Net Core v3.1(.404).

I'm to lazy to work with VS Code so think these remote debuggers are a great idea :)

**Comment by jefflill** [comment] 2020-11-20 20:12
I agree, VS Code is OK but I'm used to Visual Studio and I have multiple monitors so I want to have multiple windows open.

I'll try to replicate this and I've bugged a friend to try it too.  I wonder perhaps if I need to deploy a different version of VSDBG to the Raspberry.

**Comment by jefflill** [comment] 2020-11-20 20:21
Looks like the .NET runtime team is tracking this here: 

https://github.com/dotnet/runtime/issues/44745

**Comment by jefflill** [comment] 2020-11-22 20:55
I've been able to replicate this now for Raspberry Debugger too.  I missed this in my early testing because the project was still targeting .NET Core and a .NET Core 3,1 SDK was already installed on the Raspberry.

#16 **.NET Core SDK not installed on Raspberry when .NET 5 SDK is installed on workstation**

was also preventing folks from downgrading to .NET Core 3.1.x because the debugger wouldn't install a .NET Core 3.1 SDK due to a misunderstanding about how `dotnet --info` works.  This is corrected now.

---

So, this is still a bug that the .NET Runtime folks will have to fix: dotnet/runtime#44745.  Hopefully this will work again when MSFT publishes the next .NET 5 SDK.  I'll keep this issue open as a reminder to check for a new SDK.

...at least you can downgrade to .NET 3.1 now and use the Raspberry Debugger

**Comment by jefflill** [comment] 2020-12-02 20:22
The .NET folks have been able to reproduce this now and are working on a fix.  The problem looks like it might be constrained to Raspberry's with more than 2 GiB RAM.

x: dotnet/runtime#44745

**Comment by jefflill** [comment] 2020-12-08 20:04
I noticed that .NET 5.0.1 has been released but it doesn't include a fix for dotnet/runtime#44745

**Comment by aroenK** [comment] 2021-02-27 10:23
Hi,

Is this issue resolved in the latest version of  .Net core?

Because if I query the current version of the dotnet on my machine I get
NET SDK (reflecting any global.json):
 Version:   5.0.103

**Comment by jefflill** [comment] 2021-02-27 17:00
Sorry, I've been heads-down on another project for the past couple months.  I'll check out the latest .NET 5 releases.

**Comment by jefflill** [comment] 2021-02-27 17:23
It looks like this **fix** made it into the **5.0.102 SDK release**.

I'll do a bit of testing and publish a new version of the debugger extension.

**Comment by jefflill** [comment] 2021-02-27 17:59
@aroenK: I just published v1.2 to the Visual Studio Marketplace which enables .NET 5.0 support (skipping the 5.0.0 and 5.0.1 SDKs).

It can take some time for the VS market place to actually make updated extensions available, but if you need this immediately, you can install it from the GitHub release here:

https://github.com/nforgeio/RaspberryDebugger/releases/tag/v1.2

**Closed by jefflill** 2021-02-27 17:59 UTC
Labels: bug

**Comment by aroenK** [comment] 2021-03-03 19:18
Thx a bunch!
